### ISSUE TITLE
Empty json array encodes to `null`.

### ISSUE THREAD

**Issue by malud** [avenga/couper#162]
**Describe the bug**
The array may evaluate to `null` and therefore encodes respectively to `null`.

**To Reproduce**
1. Which Couper version? Run `couper version` or `docker run --entrypoint=/couper avenga/couper version`
`master 2021-03-29 acfce46`
2. Provide your configuration file `*.hcl`. Remove sensitive data.

```hcl
server "custom-response" {
  endpoint "/**" {
    request {
      url = "https://httpbin.org/anything?a=${req.id}"
      body = json_encode({
        foo = []
        bar = ["bar"]
      })
    }
    response {
      body = json_encode(beresp.json_body.json)
    }
  }
}
```

3. Provide a `curl` call for reproduction

`curl -v http://localhost:8080/`

Result:
```
$ http localhost
HTTP/1.1 200 OK
Connection: close
Content-Encoding: gzip
Content-Length: 47
Date: Thu, 18 Mar 2021 18:02:26 GMT
Server: couper.io
Vary: Accept-Encoding
```

```json
{"bar": ["bar"], "foo": null }
```

**Expected behavior**
```json
{"bar": ["bar"], "foo": []}
```

**Comment by filex** [comment]
Could be related to #165
