### ISSUE TITLE
Explicitly pass non-json upstream response body `backend_responses.<label>.body`

### ISSUE THREAD

**Issue by filex** [avenga/couper#182]
When I define an upstream request with a label (other than `default`), I have to define a `response{}`, too. Because otherwise Couper wouldn't know what to pass downstream.

It is straight-forward to define response status and headers. But currently I cannot simply copy the response body:

```hcl
server "pass" {
  endpoint "/teapot" {
    request "st" {
      url = "https://httpbin.org/status/418"
    }
    response {
      status = backend_responses.st.status
      headers = backend_responses.st.headers
      body = backend_responses.st.body
    }
  }
}
```

… because `backend_responses.<label>.body` doesn't exist :)

We should provide the de-chunked, de-compressed bytes of the response body in that property. E.g. to allow for useless string expressions like

```
 "Body was: ${backend_responses.st.body}"
```

The string must also be binary-safe to pass arbitrary content, e.g. pass a PDF generated by an upstream service. (And a binary-string containing a null byte shouldn't truncate the value :))

At first, it's not about optimizing this kind of operation. We can buffer the download, pull the bytes it through the expression evaluation and then compress them on the way to the client.

**Comment by johakoch** [comment]
What about `request.body`? New issue?

**Comment by filex** [comment]
> What about `request.body`?

Good idea. We can cover this here, too.

Can you provide a request configuration that would (more or less) mimic a proxy?

**Comment by johakoch** [comment]
Also, `backend_requests.<label>` has no `.json_body` and no `.body` (only `.form_body`)

**Comment by johakoch** [comment]
@filex 
> Can you provide a request configuration that would (more or less) mimic a proxy?

Something like
```hcl
request {
  method = request.method
  url = "https://some.other.host/path/to${request.path}"
  headers = request.headers
  body = request.body
}
```
?
