### ISSUE TITLE
Don't gzip small responses

### ISSUE THREAD

**Issue by filex** [avenga/couper#186]
**Describe the bug**

gzip is means to make a response smaller. However, there is a small overhead for gzip itself making it unsuitable for very small responses.

**To Reproduce**
1. Which Couper version? `0.8`
2. Provide your configuration file `*.hcl`. Remove sensitive data.

```hcl
server "gzip" {
 endpoint "/" {
  response {
    body =  ""
  }
 }
}
```

3. Provide a `curl` call for reproduction

```shell
$ curl --compressed -i http://localhost:8080/
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: text/plain
Server: couper.io
Vary: Accept-Encoding
Date: Wed, 07 Apr 2021 15:59:25 GMT
Content-Length: 23

```

Couper sends 23 bytes of body (plus 22 bytes for the  `Content-Encoding` header).

**Expected behavior**

Very small responses like that should not be gzip'ed, regardless of the client's `accept-encoding` header.

We should use a minimal body length before choosing gzip. 60 bytes could be a good start. If the response to be send is shorter, don't gzip, don't set `Content-Encoding: gzip` and don't add `accept-encoding` to the `Vary` list.

**Comment by alex-schneider** [comment]
Done with #256
