### ISSUE TITLE
Add a http health check

### ISSUE THREAD

**Issue by malud** [avenga/couper#2]
A basic requirement is to provide a configurable health check status for our own server.

We have defined some health specific requirements:

- [x] has a configurable route which defaults to `/healthz`
- [x] check must work with http 1.0 and without `host` or `xfh`
- [x] `path` match only which allows queries too
- [x] mark health check within access log (searchable field)
- [x] send `Cache-Control` with `no-store`
- [x] handle shutdown signal and serve status `500` while the server is closing

**Comment by filex** [comment]
> mark health check within access log (searchable field)

we could log a `handler` field, which can be `health` (and `files`, `spa`, `api`)

**Comment by filex** [comment]
the health request should contain a response body. many tools (haproxy, kube…) like to check a string in a healthy response.

if healthy:

`content-type: text/plain`
body: `healthy`

on error:
`error`

on shutdown:
`shutting down`
