### ISSUE TITLE
OpenAPI upstream request/response validation

### ISSUE THREAD

**Issue by johakoch** [avenga/couper#21]
We want to prevent invalid upstream request and responses which does not match the requirements from a given openAPI yaml file.

- [ ] implementation
- [ ] documentation

**Comment by johakoch** [comment]
This feature is currently configured by
``` hcl
swagger_definition = "path/to/swagger.yml"
validate_request = true
validate_response = true
```
in a `backend()` block

**Comment by johakoch** [comment]
The github.com/getkin/kin-openapi library is very handy for OpenAPI version 3. If you have a version 2 (Swagger) definition it's a lot more work. Do we need version 2 for the MVP?

**Comment by malud** [comment]
> [...]. Do we need version 2 for the MVP?
We don't need v2 support for now.

**Comment by malud** [comment]
> This feature is currently configured by
> 
> ```terraform
> swagger_definition = "path/to/swagger.yaml"
> validate_request = true
> validate_response = true
> ```
> 
> in a `backend()` block

We should name it `swagger_file` since all couper file references has a *file* suffix.

**Comment by johakoch** [comment]
Or `openapi_file`, if `swagger_file` sounds too v2-ish?

**Comment by malud** [comment]
> Or `openapi_file`, if `swagger_file` sounds too v2-ish?

sounds good.

**Comment by johakoch** [comment]
Concerning the validation of a route "not in basePath": In OpenAPI 3 there is no `basePath`. However there is a `servers` array.

Now, with the following openapi.yaml

```yaml
...
servers:
- url: https://httpbin.org:443/status/
paths:
  ...
```

the kin-openapi library does validate a request to https://httpbin.org:443/post and then state that it is an "invalid route", despite the URL not being "covered" by the openapi definition.

Looks like every URL not corresponding to a route defined in the openapi definition is treated by the router as an "invalid route".

**Comment by johakoch** [comment]
In Swagger 2, URLs could have the same host as the one defined in the swagger definition and a scheme defined in the swagger definition, but not a path "in the basePath". These URLs are somewhat undefined wrt the swagger definition.
