### ISSUE TITLE
Documentation: json-doc(path) must be relative to calling flow

### ISSUE THREAD

**Issue by openmindculture** [avenga/couper#28]
[json-doc()](https://sevenval.gitbook.io/flat/reference/functions/json-doc) expects a path to a json file. If we use `json-doc()` in an xpath inside a file which has been called from another file, the json-doc path must not be relative to the current file but to the original caller, i.e.

conf/flow.xml:
```
<xslt in="$preResult" src="./transform/transform.xsl"/>
```

`conf/transform/fields.json` contains data we want to parse.

conf/transform/transform.xsl:
```
<xsl:variable name="fieldList" select="json-doc('./conf/transform/fields.json')"/>
```

As this behaviour might be misleading, it would be good to add an example or a hint in the documentation.

**Comment by rolandguelle** [comment]
Wrong repo?
https://github.com/sevenval/flat-docs
