### ISSUE TITLE
Support for nested struct environment mapping

### ISSUE THREAD

**Issue by malud** [avenga/couper#30]
Currently we are able to map environment variables to configuration structs via tag.

An example:

```go
type Config struct {
  DefaultPort int `env:"default_port"`
}
```

This gets internally prefixed with `COUPER_` and uppercased. The value of `COUPER_DEFAULT_PORT` will be assigned to `Config.DefaultPort`.

The following example is not possible at this moment but should:

```go
type Config struct {
  DefaultPort int `env:"default_port"`
  Timings Timings
}

Type Timings struct {
  Timeout time.Duration `env:"timeout"`
}
```

Env `COUPER_TIMEOUT` must be assigned to `Config.Timings.Timeout`.

Related files are `config/env/env.go` and `runtime/http.go` makes use of it.

**Comment by mohammed786** [comment]
Hey @malud ,

Can I take this up as a hacktoberfest task?

**Comment by malud** [comment]
Sure. Go for it.

**Comment by malud** [comment]
Since we are calling our env mapping function for related structs directly this is not a requirement anymore.
