### ISSUE TITLE
Support for an UUID option as request-id

### ISSUE THREAD

**Issue by malud** [avenga/couper#31]
Couper generates a unique request id with the help of https://github.com/rs/xid .
Some projects have a requirement of a _real_ uuid which should be sent along with the request.
To provide a good log correlation, couper should be able to generate those via configuration.

The correct place for this would be the `settings` block within our couper configuration file.

```hcl
settings {
  request_id_format = "uuid4"
}
```

Default should be `common` which would be the current behaviour with the `xid` package.
If the user configure the value `uuid4` another generation method should be mapped to the `uidFn` Field of the [`HTTPServer` struct](https://github.com/avenga/couper/blob/master/server/http.go#L29). 

Since all `settings` are mapped to `config/runtime/HTTPConfig` this one must be configurable via `COUPER_REQUEST_ID_FORMAT` and command flag `-request-id-format`.

Depends on PR https://github.com/avenga/couper/pull/29 due to the `settings` block.

Pick a stable uuid package.

**Comment by RhnSaxena** [comment]
I want to solve this issue. @malud please assign this to me.

**Comment by cvhariharan** [comment]
Hi, I can pick this up if this is still open
