### ISSUE TITLE
check and log ulimits on startup

### ISSUE THREAD

**Issue by malud** [avenga/couper#327]
We would like to check the current ulimit for our Couper process. Especially in docker environments this information could be very helpful.

Check and log the current and max system settings. If the number is below a constant threshold, lets start with `4096`, log as *warn* level.

Implementation could take place within the `run` command.

**Comment by wisdommatt** [comment]
@malud i will like to work on this

**Comment by wisdommatt** [comment]
@malud the only package that contains `ulimits` in the codebase is `github.com/docker/go-units` in vendor directory, what package am i supposed to use to get the ulimits ?

**Comment by malud** [comment]
@wisdommatt you must use the https://pkg.go.dev/syscall#Getrlimit package to get this system related information.

**Comment by wisdommatt** [comment]
@malud the tests fails on my machine when i run `make test` even when i have not updated the codebase, are there any software/dependencies i need to install on my machine to make the tests pass ?

**Comment by wisdommatt** [comment]
@malud the tests are still failing on my machine

**Comment by wisdommatt** [comment]
@malud i just updated the PR, everything is now working fine
