### ISSUE TITLE
block `label` differs in implementation and documentation

### ISSUE THREAD

**Issue by wilhelmmailaender** [avenga/couper#49]
In the documentation the `label` is optional for the `server`, `api`, `spa` and `files` block. 

But the implementation differs. The `label` is required for `server`, and not allowed for `api`, `spa` and `files`. Other blocks may be also differ between implementation and documentation.

The implementation should make the `label` optional for all blocks, as it is in the documentation.

**Comment by malud** [comment]
We should adapt the docs for now. The `server` label is required and not designated for `files` `spa` and `api` (currently).

/cc @filex
