### ISSUE TITLE
Handle deprecated blocks or attributes on hcl.syntax level

### ISSUE THREAD

**Issue by malud** [avenga/couper#725]
> Note: enhancement from code perspective which will solve a current bug.

In general we need a component which acts as syntax pre-processor to rename deprecated `block`, `attribute` or `error_handler` names/types. Additionally we can log such a rename once with a warning and a hint for the upcoming version which will drop the support for the old names. For example our beta_ features.

A current situation for the beta_permissions should be fixed since Couper does not understand the old _beta__ permission prefix. See #673 .

Should be executed after our config-merge pre-processor.

Rough data format:
`[type][key]struct{new: val, version: upcoming}` and key (e.g. `beta_permission`) should refer to the old one for easy lookups. Type could be `block`,`attribute` or `error_handler`.

**Comment by alex-schneider** [comment]
> Should be executed after our config-merge pre-processor.

We must deprecate **bevore** merge process, because we call `validate()` for each parsed body.

**Comment by johakoch** [comment]
> What about the renamed `beta_granted_permissions` and `beta_required_permission` request context variables?

I guess that it's not so easy to find references to `request.context.beta_granted_permissions` or `request.context.beta_required_permission`, change them and log a warning.

However, in eval/context.go
```go
func newVariable(ctx context.Context, cookies []*http.Cookie, headers http.Header) ContextMap {
...
	gp, _ := ctx.Value(request.GrantedPermissions).([]string)
	if len(gp) > 0 {
		ctxAcMap[grantedPermissions] = seetie.GoToValue(gp)
	}
	if rp, permissionSet := ctx.Value(request.RequiredPermission).(string); permissionSet {
		ctxAcMap[requiredPermission] = seetie.GoToValue(rp)
	}
```
we could additionally store the values under `beta_`-prefixed keys.

There will only be values if permission-related attributes are configured. And if these are `beta_`-prefixed, there will be log warnings.

**Comment by johakoch** [comment]
https://github.com/avenga/couper-vscode/pull/126 added a message containing the version _with_ which a feature was deprecated. Now that, in Couper, we have a version, _until_ which a deprecated feature is still supported, should we add this to the VSCode message, too?

**Comment by johakoch** [comment]
> [avenga/couper-vscode#126](https://github.com/avenga/couper-vscode/pull/126) added a message containing the version with which a feature was _deprecated_. Now that, in Couper, we have a version, with which a deprecated feature is _no longer supported_, should we add this to the VSCode message, too?

https://github.com/avenga/couper-vscode/pull/129
