### ISSUE TITLE
Security check for Upstream Request Validation

### ISSUE THREAD

**Issue by johakoch** [avenga/couper#76]
If the OpenAPI3 description of an upstream API mentions security requirements (`security`) for routes, Couper should perform security checks when validating requests to this upstream API (according to the referenced security scheme objects in `components.securitySchemes`):

* type: `http`
  * scheme: `basic`: header "`Authorization: Basic ...`" set?
  * scheme: `bearer`: header "`Authorization: Bearer ...`" set?
* type: `apiKey`
  * in: `query`; name: `<query_param>`: query parameter `<query_param>` set?
  * in: `header`; name: `<header_name>`: header `<header_name>` set?
  * in: `cookie`; name: `<cookie_name>`:  cookie `<cookie_name>` set?
* type: `oauth2`/`openIdConnect`: header "`Authorization: Bearer ...`" set?

If `security` references several security scheme objects, the requirements must be `AND`ed or `OR`ed accordingly.

This additional check should be configurable (default is ~~`on`~~`true`~~; performed only if upstream request validation is `on`~~).

**Comment by johakoch** [comment]
For `type: http`, `scheme: bearer` OpenAPI 3 also specifies a `bearerFormat` property with the description
> A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.

The example in https://swagger.io/docs/specification/authentication/bearer-authentication/ has a `bearerFormat` value of `JWT`. However this is not a reserved name and so cannot be used as a trigger for more elaborate checks (whether the token presented in the `Authorization` header is actually a JWT consisting of three parts, the first two of which can be base64url-decoded, ...)

**Comment by malud** [comment]
We still missing a use-case to check those values. Couper can't verify the given values since its a backend task finally.
